### ISSUE TITLE
crabby.py does not accept lumiMask argument

### ISSUE THREAD

**Issue by garvitaa** [cms-jet/PFNano#36]
I'm submitting crab jobs using the handler script, I have appropriately modified `card_example.yml`, but the `--lumiMask ` argument does not work. I've tried placing it in different orders w.r.t `--make` and `--submit` but all attempts end in the same error.
I'm using the instructions here: https://github.com/cms-jet/PFNano#processing-data

```
$ python crabby.py -c card_example.yml --make --lumiMask jsons/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.txt --submit
usage: crabby.py [-h] [-c CARD] [--make] [--submit] [--status]
                 [--test {False,True}]
crabby.py: error: unrecognized arguments: --lumiMask jsons/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.txt
```

**Comment by andrzejnovak** [comment]
@garvitaa Seems I missed that bit in the readme. There's a place for lumiMask in the card https://github.com/cms-jet/PFNano/blob/master/test/card_example.yml#L19

**Comment by garvitaa** [comment]
Thanks. That resolves the issue for me.
