### ISSUE TITLE
Processing MiniAODv3 (12_4_X) vs MiniAODv4 (13_0_X)

### ISSUE THREAD

**Issue by alejands** [cms-jet/PFNano#57]
Dear cms-jet developers,

I am trying to use your PFNano code to generate some custom NanoAODs that include PF candidates for training the algorithm used to calculate MET at the trigger level.

The PFNano branch I'm currently using is `13_0_7_from124MiniAOD`, but one of the datasets I need to run on, `Zto2Nu`, is only available in MiniAODv4, which is created using CMSSW_13_0_X.

Do you know if this branch can be used to process this MiniAODv4 correctly, or can it only be used on MiniAODv3 (created using CMSSW_12_4_X)? If this PFNano code is not compatible with MiniAODv4, will there be support for this format soon, or is there a way to make this compatible?

Many thanks,
Alejandro

**Comment by Senphy** [comment]
Dear Alejandro,

Unfortunately, the current branch 13_0_7_from124MiniAOD cannot be used to process MiniAODv4 due to the differences in GTs and conditions. We are in the process of creating a new branch specifically for MiniAODv4, and it will be completed soon. Sorry for the inconvenience. 

Best Regards,
Sen

**Comment by Ming-Yan** [comment]
Hi @alejands apologize at the moment we have move the development combined with NanoAOD with customized modules which provides the same  contents as used in PFNano and support by `MiniAODv4`

We create a merge topic for this version 
`git cms-merge-topic Ming-Yan:130X-fixPuppi_NanoV12` 

https://github.com/Ming-Yan/cmssw/tree/130X-fixPuppi_NanoV12

Where the cmsDriver command can be found here 
https://github.com/cms-btv-pog/btvnano-prod/tree/NanoAODv12_22Sep2023#notes-for-developer-tbd

Hope this helps!

**Comment by alejands** [comment]
Thanks @Ming-Yan! Is the plan to migrate future PFNano updates directly into CMSSW?

**Comment by Ming-Yan** [comment]
exactly :)
